/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as PriceListsRouteImport } from './routes/price-lists'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PriceListsIdRouteImport } from './routes/price-lists.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceListsRoute = PriceListsRouteImport.update({
  id: '/price-lists',
  path: '/price-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceListsIdRoute = PriceListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PriceListsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/price-lists': typeof PriceListsRouteWithChildren
  '/products': typeof ProductsRoute
  '/price-lists/$id': typeof PriceListsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/price-lists': typeof PriceListsRouteWithChildren
  '/products': typeof ProductsRoute
  '/price-lists/$id': typeof PriceListsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/price-lists': typeof PriceListsRouteWithChildren
  '/products': typeof ProductsRoute
  '/price-lists/$id': typeof PriceListsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/categories' | '/price-lists' | '/products' | '/price-lists/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories' | '/price-lists' | '/products' | '/price-lists/$id'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/price-lists'
    | '/products'
    | '/price-lists/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  PriceListsRoute: typeof PriceListsRouteWithChildren
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-lists': {
      id: '/price-lists'
      path: '/price-lists'
      fullPath: '/price-lists'
      preLoaderRoute: typeof PriceListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-lists/$id': {
      id: '/price-lists/$id'
      path: '/$id'
      fullPath: '/price-lists/$id'
      preLoaderRoute: typeof PriceListsIdRouteImport
      parentRoute: typeof PriceListsRoute
    }
  }
}

interface PriceListsRouteChildren {
  PriceListsIdRoute: typeof PriceListsIdRoute
}

const PriceListsRouteChildren: PriceListsRouteChildren = {
  PriceListsIdRoute: PriceListsIdRoute,
}

const PriceListsRouteWithChildren = PriceListsRoute._addFileChildren(
  PriceListsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  PriceListsRoute: PriceListsRouteWithChildren,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
